name: bargina
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.3+5

environment:
  sdk: '>=2.18.5 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  get_it: ^7.2.0
  get:
  cloud_firestore: ^3.1.0
  # firebase_storage: ^10.1.0
  easy_localization: ^3.0.0
  http: ^0.13.4
  json_serializable: ^6.1.3
  dots_indicator: ^2.0.0
  flutter_rating_bar: ^4.0.0
  flutter_svg:
  sms_autofill: ^2.2.0
  flutter_screenutil: ^5.0.0+2
  cached_network_image: ^3.2.0
  hexcolor: ^2.0.5
  badges: ^2.0.1
  chips_choice: ^2.0.1
  rflutter_alert: ^2.0.4
  dio: ^4.0.4
  url_launcher: ^6.0.17
  uuid: ^3.0.5
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.12
  path_provider: ^2.0.8
  shimmer: ^2.0.0
  google_sign_in: ^5.2.2
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  image_picker: ^0.8.4+4
  dotted_line: ^3.1.0
  flutter_switch: ^0.3.2
  page_indicator: ^0.4.1
  sqflite: ^2.0.0+3
  path: ^1.8.0
  pin_code_fields: ^7.4.0
  flutter_slidable: ^1.2.0
  flutter_login_facebook: ^1.4.1
  expandable_page_view:
  awesome_dialog: ^2.2.1
  internet_connection_checker: ^0.0.1+3
  connectivity_plus: ^1.0.0
  flutter_keyboard_visibility: ^5.0.3
  intl: ^0.17.0
  flutter_lints: ^2.0.0
  purchases_flutter: ^4.3.1
  the_apple_sign_in:
  pay:

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/ar-EG.json
    - assets/translations/en-US.json
    - assets/mada.png
    - assets/visa.png
    - assets/master.png
    - assets/props/
    - assets/icons/
    - assets/icons/filter.png
    - assets/icons/filter1.png
    - assets/icons/edit.png
    - assets/icons/Approved.png
    - assets/icons/deleat.png
    - assets/icons/status.png
    - assets/icons/retry.png
    - assets/icons/no_internet.png
    - assets/icons/Terms_Icon.png
    - assets/images/error_image.png
    - assets/images/poly.png
    - assets/images/banner.png
    - assets/images/logo.png
    - assets/images/splash_logoo.PNG
    - assets/images/logo_splash.PNG

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  fonts:
    - family: jannah
      fonts:
        - asset: assets/fonts/jannah.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
